// Auto-generated by Gateway Connection prompt
// Update these URLs when cloud-passport/ is deployed
//
// PRODUCTION NOTE:
// When cloud-passport/ is deployed to AWS Amplify or a custom domain,
// set VITE_PASSPORT_URL in website/ environment variables.
// No code change needed — this file reads from the env var automatically.

const PASSPORT_BASE_URL = import.meta.env.VITE_PASSPORT_URL || 'http://localhost:5173'

export const PASSPORT_LINKS = {
  initialize: `${PASSPORT_BASE_URL}/join`,
  terminal: `${PASSPORT_BASE_URL}/login`,
  create: `${PASSPORT_BASE_URL}/join`,
}
